### ISSUE TITLE
Incorrect year

### ISSUE THREAD

**Issue by papersaltserver** [yeo/betterdev.link#22]
Hello and Happy New Year.
The last 2 issues were sent with year 2020 :)

**Comment by v9n** [comment]
Thank you. It should be fixed now :-).
<img width="708" alt="Screen Shot 2021-01-15 at 7 49 15 AM" src="https://user-images.githubusercontent.com/49754/104748107-2d845680-5706-11eb-93ff-8c89ab8bc64a.png">
