### ISSUE TITLE
RSS item order bug

### ISSUE THREAD

**Issue by yandd** [yeo/betterdev.link#3]
See PR #2

**Comment by kureikain** [comment]
Thanks a lot @yandd

**Comment by kureikain** [comment]
@yandd Thanks you for your help. I also put up contributor page: https://github.com/yeo/betterdev.link/blob/0f7aaad9b699ee7d33bb917337ff9c3232c9dc2e/CONTRIBUTOR.md Feel free to link it to your personal site as well.
