### ISSUE TITLE
RSS is invalid

### ISSUE THREAD

**Issue by yandd** [yeo/betterdev.link#4]
https://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fbetterdev.link%2Frss.xml

Solution:
https://stackoverflow.com/questions/11993258/what-is-the-correct-format-for-rss-feed-pubdate
https://www.w3.org/Protocols/rfc822/#z28

**Comment by kureikain** [comment]
@yandd Thanks. It should be fixed now. Are you the same person that email me about the bug. Thanks  alot.

**Comment by yandd** [comment]
@kureikain Yes, it's me. After sended the email, I found  the github repo of "betterdev.link" . :smile:

**Comment by kureikain** [comment]
@yandd I made you a contributor. Now, you can push any code to this repository without sending PR. Thanks a lot for other contribution as well.
